#Point 1
# Polymorphism की जरूरत क्यों पड़ी? पहले word समझो: Poly = ManyMorph = Forms
# तो simple meaning:Polymorphism = One thing, many forms.
# Programming में इसका मतलब है:Same method/function call, लेकिन object के हिसाब से अलग-अलग behaviour.

# without polymorphism:
if model_type == "openai":
    openai.generate()

elif model_type == "gemini":
    gemini.generate()

elif model_type == "claude":
    claude.generate()
# ProblemBusiness code को हर बार पता होना चाहिए:कौन सा object आया है?
# और हर नए implementation पर main code modify करना पड़ रहा है।
# यहीं polymorphism useful होता है।
# हम सभी objects को same operation देते हैं:generate()  लेकिन हर object उसका अपना version execute करता है।
# openai.generate()gemini.generate()claude.generate() Method name same: generate() Behaviour अलग।यही polymorphism का core idea है।
class OpenAI:
    def generate(self):
        print("Response generated by OpenAI")
class Gemini:
    def generate(self):
        print("Response generated by Gemini")
openai = OpenAI()
gemini = Gemini()
openai.generate()# response generated by OpenAI
gemini.generate()#response generated by Gemini

# IN JAVA

# class Animal {
#     void sound() {
#         System.out.println("Animal sound");
#     }
# }
# class Dog extends Animal {
#     @Override
#     void sound() {
#         System.out.println("Dog barks");
#     }
# }
# class Cat extends Animal {
#     @Override
#     void sound() {
#         System.out.println("Cat meows");
#     }
# }
# public class Main {
#     public static void main(String[] args) {

#         Animal a1 = new Dog();
#         Animal a2 = new Cat();

#         a1.sound();   // Dog barks
#         a2.sound();   // Cat meows
#     }
# }








#Point 2 
# Java: polymorphism commonly parent class/interface के through होता है.
# Python: parent class optional है; same required method होना enough हो सकता है.
# यहाँ Dog और Cat किसी Animal class से inherit नहीं कर रहे.
# फिर भी काम कर रहा है क्योंकि दोनों के पास same method है:
class Dog:
    def sound(self):
        print("Dog barks")
class Cat:
    def sound(self):
        print("Cat meows")
def make_sound(animal):
    animal.sound()
make_sound(Dog())
make_sound(Cat())
# Python बस ये देखता है:जो object आया है, उसके पास sound() method है या नहीं?
# इस approach को आगे Duck Typing बोलते हैं.Java में usually ऐसा नहीं कर सकते:
#JAVA EQUIVALENT 
# class Animal {
#     void sound() {
#         System.out.println("Animal sound");
#     }
# }
# class Dog extends Animal {
#     @Override
#     void sound() {
#         System.out.println("Dog barks");
#     }
# }
# class Cat extends Animal {
#     @Override
#     void sound() {
#         System.out.println("Cat meows");
#     }
# }
# public class Main {

#     static void makeSound(Animal animal) {
#         animal.sound();
#     }

#     public static void main(String[] args) {

#         makeSound(new Dog());   // Dog barks
#         makeSound(new Cat());   // Cat meows
#     }
# }










#pOINT 3 
# Java में polymorphism को तुम mostly दो parts में पढ़ते हो:
# 1. Method Overloading → Compile-time polymorphism 2. Method Overriding → Runtime polymorphism
# Python में situation थोड़ी अलग है।
# 1. Method Overriding — Python में भी होता है 2. Method Overloading — Python में Java जैसा directly नहीं होता

#OVERIDING
class Animal:
    def sound(self):
        print("Animal sound")
class Dog(Animal):
    def sound(self):          # overriding
        print("Dog barks")
dog = Dog()
dog.sound() #Dog barks

# Java equivalent:
# class Animal {
#     void sound() {
#         System.out.println("Animal sound");
#     }
# }

# class Dog extends Animal {
#     @Override
#     void sound() {
#         System.out.println("Dog barks");
#     }


#oVERLOADING
# Python में method overloading directly नहीं होता।Python में last defined method ही valid होती है
class Calculator:
   def add(self, a, b):
        return a + b
   def add(self, a, b, c): #तुम सोच सकते हो कि दोनों add() methods available होंगे। लेकिन नहीं।
        return a + b + c   #       Python में second method first method को replace कर देगा।
c = Calculator()
print(c.add(10, 20, 30))   # works
print(c.add(10, 20))       # error

# तो Python में same काम कैसे करते हैं?
# 1: Default Arguments
class Calculator:
     def add(self, a, b, c=0):
        return a + b + c
c = Calculator()
print(c.add(10, 20))       # 30
print(c.add(10, 20, 30))   # 60

# 2: *args
class Calculator:
     def add(self, *numbers):
        return sum(numbers)
c = Calculator()
print(c.add(10, 20))
print(c.add(10, 20, 30))
print(c.add(1, 2, 3, 4, 5))


# JAVA EQUIVALENT
# class Calculator {
#    int add(int a, int b) {
#         return a + b;
#     }
#    int add(int a, int b, int c) {
#         return a + b + c;
#     }
#     double add(double a, double b) {
#         return a + b;
#     }
# }
# public class Main {
#     public static void main(String[] args) {

#         Calculator c = new Calculator();

#         System.out.println(c.add(2, 3));        // 5
#         System.out.println(c.add(2, 3, 4));     // 9
#         System.out.println(c.add(2.5, 3.5));    // 6.0
#     }
# }


# ये Python में polymorphism का बहुत अच्छा example है.Operator Overloading क्या है?
print(10 + 20) # 30 ADDITION 
print("Hello " + "World") #Hello World CONCATINATON
# Java में भी थोड़ा similar होता है Java में:
# System.out.println(10 + 20);           // 30
# System.out.println("Hello " + "World"); // Hello World

# लेकिन Java में तुम custom classes के लिए operators को freely overload नहीं कर सकते.
# Python में कर सकते हो.
# ये Python के special methods हैं, जिन्हें dunder methods कहते हैं। Dunder = Double UnderScore
# +   → __add__()
# -   → __sub__()
# *   → __mul__()
# /   → __truediv__()
# ==  → __eq__()
# <   → __lt__()
# >   → __gt__()
class Number:
    def __init__(self, value):
        self.value = value

    def __add__(self, other):
        return self.value * other.value
n1 = Number(10)
n2 = Number(20)
print(n1 + n2) #200  # 10 * 20 = 200
# जब तुम लिखते हो:n1 + n2 Python internally लगभग ऐसा करता है:
# n1.__add__(n2)मतलब:self  = n1other = n2
# अब __add__() के अंदर:return self.value * other.value
# इसलिए output 200 आया।
# अब interesting point यह है कि operator + है, लेकिन तुमने उसके अंदर multiplication करा दिया:

# अगर __add__() नहीं बनाते:
class Number:
    def __init__(self, value):
        self.value = value
n1 = Number(10)
n2 = Number(20)
print(n1 + n2) #TypeError: unsupported operand type(s) for +: 'Number' and 'Number'ku ki build in + operator को पता नहीं है 
# कि object  n1 and  n2 ko kaise add karna hai. ku ki wo int ya str नहीं है। 












# Point 4 Duck Typing in Python
#  Duck Typing Python polymorphism ka bahut important concept hai. Simple idea:
# Python ko object ki exact class se zyada fark nahi padta.Bas object ke andar required method hona chahiye.
#Famous idea:"If it walks like a duck and quacks like a duck, treat it like a duck."
#Programming meaning:Agar object required behaviour provide karta hai, to Python us object ko use kar sakta hai.
class Dog:
    def sound(self):
        print("Dog barks")
class Robot:
    def sound(self):
        print("Robot beeps")
def make_sound(obj):
    obj.sound()
make_sound(Dog())      # Dog barks
make_sound(Robot())    # Robot beeps


# Important: Dog aur Robot ka koi inheritance relation nahi hai.Dog kisi common Animal class se inherit nahi kar raha.
# Robot bhi kisi common Animal class se inherit nahi kar raha. Fir bhi make_sound() dono ke saath kaam kar raha hai.
# Reason: Dono objects ke paas sound() method hai.
#  Python basically yeh nahi pooch raha:"Kya tum Animal class ke object ho?"
# Python yeh dekh raha hai: "Kya tumhare paas sound() method hai?"
# Agar haan -> method call kar do. Agar required method nahi hua:
class Car:
    pass
#  make_sound(Car()) AttributeError: 'Car' object has no attribute 'sound'


# JAVA EQUIVALENT
# -------------------------------------------------

# Java me normally same kaam karne ke liyecommon parent class ya interface use karte hain.
#interface Soundable {
#     void sound();
# }
#class Dog implements Soundable {
#
#     public void sound() {
#         System.out.println("Dog barks");
#     }
# }
#class Robot implements Soundable {
#public void sound() {
#         System.out.println("Robot beeps");
#     }
# }
#static void makeSound(Soundable obj) {
#     obj.sound();
# }
# makeSound(new Dog());
# makeSound(new Robot());

#
# Java:
# "Tell me your type/interface first."
# Python:
# "I don't care about your exact type.
#  Just show me that you can perform the required behaviour."


# import java.util.*;

# public class Main {

#     // Python len() jaisa
#     static int len(String s) {
#         return s.length();
#     }

#     static int len(int[] arr) {
#         return arr.length;
#     }

#     static int len(List<Integer> list) {
#         return list.size();
#     }


#     // Python max() jaisa
#     static int max(int[] arr) {
#         int maximum = arr[0];

#         for (int num : arr) {
#             if (num > maximum) {
#                 maximum = num;
#             }
#         }

#         return maximum;
#     }

#     static char max(String s) {
#         char maximum = s.charAt(0);

#         for (char ch : s.toCharArray()) {
#             if (ch > maximum) {
#                 maximum = ch;
#             }
#         }

#         return maximum;
#     }


#     public static void main(String[] args) {

#         System.out.println(len("Harshit"));              // 7
#         System.out.println(len(new int[]{10,20,30}));   // 3
#         System.out.println(len(Arrays.asList(1,2,3,4))); // 4

#         System.out.println(max(new int[]{4,9,2,7}));    // 9
#         System.out.println(max("abc"));                  // c
#     }
# }
